//! Contextual follow-up module for the Copilot Engine.
//!
//! Generates intelligent follow-up suggestions based on the current
//! recommendation context, user history, and engineering workflow state.
//!
//! Follow-ups are context-aware suggestions that build upon previous
//! recommendations and user interactions to guide engineers toward
//! optimal outcomes.
//!
//! ## How It Works
//!
//! 1. **Analyze** the current recommendation and its context
//! 2. **Consider** user history and past interactions
//! 3. **Generate** 1-3 contextual follow-up suggestions
//! 4. **Rank** by relevance and estimated value
//!
//! ## Priority
//!
//! Follow-ups inherit the priority of their parent recommendation,
//! allowing the policy engine to filter them appropriately.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{Confidence, Priority, Recommendation};

/// A single follow-up suggestion generated by the copilot.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FollowUpSuggestion {
    /// Unique identifier for this follow-up.
    pub id: Uuid,
    /// Parent recommendation ID.
    pub parent_recommendation_id: Uuid,
    /// Short title of the follow-up.
    pub title: String,
    /// Detailed description of why this follow-up is relevant.
    pub description: String,
    /// Confidence that this follow-up is useful.
    pub confidence: Confidence,
    /// Priority level inherited from parent recommendation.
    pub priority: Priority,
    /// Suggested action the user should take.
    pub suggested_action: String,
    /// Reason this follow-up was generated.
    pub reason: String,
    /// Timestamp when the follow-up was created.
    pub created_at: DateTime<Utc>,
}

impl FollowUpSuggestion {
    /// Create a new follow-up suggestion.
    pub fn new(
        parent_id: Uuid,
        title: impl Into<String>,
        description: impl Into<String>,
        suggested_action: impl Into<String>,
        reason: impl Into<String>,
        confidence: Confidence,
        priority: Priority,
    ) -> Self {
        FollowUpSuggestion {
            id: Uuid::new_v4(),
            parent_recommendation_id: parent_id,
            title: title.into(),
            description: description.into(),
            suggested_action: suggested_action.into(),
            reason: reason.into(),
            confidence,
            priority,
            created_at: Utc::now(),
        }
    }

    /// Create a low-priority informational follow-up.
    pub fn informational(
        parent_id: Uuid,
        title: impl Into<String>,
        description: impl Into<String>,
        suggested_action: impl Into<String>,
    ) -> Self {
        FollowUpSuggestion::new(
            parent_id,
            title,
            description,
            suggested_action,
            "Informational follow-up based on current context".to_string(),
            Confidence::new(0.5),
            Priority::Information,
        )
    }

    /// Create a warning-level follow-up.
    pub fn warning(
        parent_id: Uuid,
        title: impl Into<String>,
        description: impl Into<String>,
        suggested_action: impl Into<String>,
    ) -> Self {
        FollowUpSuggestion::new(
            parent_id,
            title,
            description,
            suggested_action,
            "Potential issue identified that warrants attention".to_string(),
            Confidence::new(0.7),
            Priority::Warning,
        )
    }

    /// Create a critical follow-up.
    pub fn critical(
        parent_id: Uuid,
        title: impl Into<String>,
        description: impl Into<String>,
        suggested_action: impl Into<String>,
    ) -> Self {
        FollowUpSuggestion::new(
            parent_id,
            title,
            description,
            suggested_action,
            "Urgent follow-up requiring immediate attention".to_string(),
            Confidence::new(0.9),
            Priority::Critical,
        )
    }
}

/// Contextual follow-up generation engine.
///
/// Analyzes recommendations and their context to generate
/// intelligent follow-up suggestions.
#[derive(Debug, Clone)]
pub struct ContextualFollowUp {
    /// Track generated follow-ups for deduplication.
    #[allow(dead_code)]
    generated_ids: Vec<Uuid>,
}

impl ContextualFollowUp {
    /// Create a new ContextualFollowUp instance.
    pub fn new() -> Self {
        ContextualFollowUp {
            generated_ids: Vec::new(),
        }
    }

    /// Generate follow-up suggestions for a recommendation.
    ///
    /// Analyzes the recommendation's title, description, evidence,
    /// and priority to produce 1-3 relevant follow-up suggestions.
    pub fn generate(&self, recommendation: &Recommendation) -> Vec<FollowUpSuggestion> {
        let mut suggestions: Vec<FollowUpSuggestion> = Vec::new();

        // Analyze title for follow-up opportunities
        let title_lower = recommendation.title.to_lowercase();

        if self.contains_keyword(
            &title_lower,
            &["test", "unit test", "integration", "coverage"],
        ) {
            suggestions.push(FollowUpSuggestion::warning(
                recommendation.id,
                "Consider adding more test coverage".to_string(),
                format!(
                    "The current recommendation may benefit from additional test cases. \
                     Focus on edge cases and boundary conditions related to '{}'.",
                    recommendation.title
                ),
                "Review existing tests and add coverage for uncovered scenarios.".to_string(),
            ));
        }

        if self.contains_keyword(&title_lower, &["document", "doc", "readme", "api doc"]) {
            suggestions.push(FollowUpSuggestion::informational(
                recommendation.id,
                "Documentation review recommended".to_string(),
                format!(
                    "The documentation changes suggested in this recommendation should be \
                     reviewed for consistency with existing docs. Check: {}.",
                    recommendation
                        .supporting_documents
                        .iter()
                        .take(3)
                        .cloned()
                        .collect::<Vec<_>>()
                        .join(", ")
                ),
                "Verify documentation changes align with project standards.".to_string(),
            ));
        }

        if self.contains_keyword(
            &title_lower,
            &["security", "vuln", "auth", "permission", "access"],
        ) {
            suggestions.push(FollowUpSuggestion::critical(
                recommendation.id,
                "Security follow-up required".to_string(),
                "Security-related recommendations require additional verification. \
                 Ensure all attack vectors are considered and the fix is comprehensive."
                    .to_string(),
                "Run a security review and verify the fix against known vulnerability patterns."
                    .to_string(),
            ));
        }

        if self.contains_keyword(
            &title_lower,
            &["performance", "perf", "slow", "latency", "bottleneck"],
        ) {
            suggestions.push(FollowUpSuggestion::warning(
                recommendation.id,
                "Performance validation needed".to_string(),
                "Before applying this performance recommendation, verify the baseline \
                 metrics and establish benchmarks for comparison."
                    .to_string(),
                "Measure current performance, apply changes, then re-measure to confirm improvement."
                    .to_string(),
            ));
        }

        if self.contains_keyword(
            &title_lower,
            &["refactor", "cleanup", "restructure", "debt"],
        ) {
            suggestions.push(FollowUpSuggestion::informational(
                recommendation.id,
                "Refactoring safety check".to_string(),
                "When refactoring, ensure that the public API surface remains unchanged \
                 and all dependent modules continue to compile."
                    .to_string(),
                "Run the full test suite after refactoring to confirm no regressions.".to_string(),
            ));
        }

        if self.contains_keyword(&title_lower, &["deprec", "remove", "legacy", "compat"]) {
            suggestions.push(FollowUpSuggestion::warning(
                recommendation.id,
                "Deprecation impact analysis".to_string(),
                "Before removing or deprecating functionality, verify no external consumers \
                 are relying on it. Check usage patterns in dependent crates."
                    .to_string(),
                "Search for usages across the workspace and plan a migration path for dependents."
                    .to_string(),
            ));
        }

        // Generate context-aware follow-up based on priority
        match recommendation.priority {
            Priority::Critical => {
                if suggestions.is_empty() {
                    suggestions.push(FollowUpSuggestion::critical(
                        recommendation.id,
                        "Immediate action required".to_string(),
                        "This critical recommendation requires immediate follow-up. \
                         Assess the impact and determine the fastest safe remediation."
                            .to_string(),
                        "Review the recommendation details and take action within the SLA."
                            .to_string(),
                    ));
                }
            }
            Priority::Warning => {
                if suggestions.is_empty() {
                    suggestions.push(FollowUpSuggestion::warning(
                        recommendation.id,
                        "Follow-up recommended".to_string(),
                        "This warning-level recommendation should be addressed in the current \
                         sprint or iteration. Prioritize based on business impact."
                            .to_string(),
                        "Add this recommendation to the current work queue.".to_string(),
                    ));
                }
            }
            Priority::Suggestion => {
                if suggestions.is_empty() {
                    suggestions.push(FollowUpSuggestion::informational(
                        recommendation.id,
                        "Suggestion for consideration".to_string(),
                        "This suggestion may improve the codebase or workflow. \
                         Evaluate during normal planning."
                            .to_string(),
                        "Consider adding to the backlog for future implementation.".to_string(),
                    ));
                }
            }
            Priority::Information => {}
        }

        // Add a generic "next step" follow-up based on suggested_next_step
        if let Some(next_step) = &recommendation.suggested_next_step {
            suggestions.push(FollowUpSuggestion::informational(
                recommendation.id,
                "Next step guidance".to_string(),
                format!(
                    "The recommendation includes a suggested next step: '{}'. {}",
                    next_step,
                    "Proceed with this action if it aligns with your current priorities."
                )
                .to_string(),
                next_step.to_string(),
            ));
        }

        // Deduplicate by title (case-insensitive)
        self.deduplicate(&mut suggestions);

        suggestions
    }

    /// Generate follow-ups for multiple recommendations.
    pub fn generate_batch(&self, recommendations: &[Recommendation]) -> Vec<FollowUpSuggestion> {
        let mut all: Vec<FollowUpSuggestion> = Vec::new();
        for rec in recommendations {
            all.extend(self.generate(rec));
        }
        all
    }

    /// Check if a string contains any of the given keywords.
    fn contains_keyword(&self, text: &str, keywords: &[&str]) -> bool {
        keywords.iter().any(|kw| text.contains(*kw))
    }

    /// Remove duplicate suggestions based on title similarity.
    fn deduplicate(&self, suggestions: &mut Vec<FollowUpSuggestion>) {
        let mut seen = std::collections::HashSet::new();
        suggestions.retain(|s| {
            let key = s.title.to_lowercase();
            seen.insert(key)
        });
    }
}

impl Default for ContextualFollowUp {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Confidence, Evidence, Priority};

    fn make_recommendation(
        title: impl Into<String>,
        description: impl Into<String>,
        priority: Priority,
    ) -> Recommendation {
        Recommendation::new(
            title,
            description,
            "test reason".to_string(),
            Confidence::new(0.8),
            vec![Evidence {
                source: "test".to_string(),
                description: "test evidence".to_string(),
                confidence: Confidence::new(0.8),
            }],
            priority,
            vec![],
        )
    }

    #[test]
    fn test_follow_up_new() {
        let follow_up = FollowUpSuggestion::new(
            Uuid::nil(),
            "Test Follow-up",
            "A test follow-up",
            "Take action",
            "Generated for testing",
            Confidence::new(0.5),
            Priority::Suggestion,
        );
        assert_eq!(follow_up.title, "Test Follow-up");
        assert_eq!(follow_up.priority, Priority::Suggestion);
        assert_eq!(follow_up.confidence.score, 0.5);
    }

    #[test]
    fn test_follow_up_informational() {
        let follow_up = FollowUpSuggestion::informational(
            Uuid::nil(),
            "Info Follow-up",
            "Description",
            "Action",
        );
        assert_eq!(follow_up.priority, Priority::Information);
        assert_eq!(follow_up.confidence.score, 0.5);
    }

    #[test]
    fn test_follow_up_warning() {
        let follow_up = FollowUpSuggestion::warning(Uuid::nil(), "Warn", "Description", "Action");
        assert_eq!(follow_up.priority, Priority::Warning);
        assert_eq!(follow_up.confidence.score, 0.7);
    }

    #[test]
    fn test_follow_up_critical() {
        let follow_up =
            FollowUpSuggestion::critical(Uuid::nil(), "Critical", "Description", "Action");
        assert_eq!(follow_up.priority, Priority::Critical);
        assert_eq!(follow_up.confidence.score, 0.9);
    }

    #[test]
    fn test_generate_test_keyword_follow_up() {
        let rec = make_recommendation(
            "Add unit test for authentication",
            "Tests need to be added",
            Priority::Warning,
        );
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        assert!(!suggestions.is_empty());
        assert!(suggestions.iter().any(|s| s.priority == Priority::Warning));
    }

    #[test]
    fn test_generate_security_keyword_follow_up() {
        let rec = make_recommendation(
            "Fix security vulnerability in auth module",
            "Security issue found",
            Priority::Critical,
        );
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        assert!(!suggestions.is_empty());
        assert!(suggestions.iter().any(|s| s.priority == Priority::Critical));
    }

    #[test]
    fn test_generate_performance_keyword_follow_up() {
        let rec = make_recommendation(
            "Optimize database query performance",
            "Query is slow",
            Priority::Warning,
        );
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        assert!(!suggestions.is_empty());
        assert!(suggestions.iter().any(|s| s.title.contains("Performance")));
    }

    #[test]
    fn test_generate_refactor_keyword_follow_up() {
        let rec = make_recommendation(
            "Refactor legacy code structure",
            "Code needs cleanup",
            Priority::Suggestion,
        );
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        assert!(!suggestions.is_empty());
        assert!(suggestions.iter().any(|s| s.title.contains("Refactoring")));
    }

    #[test]
    fn test_generate_deprec_keyword_follow_up() {
        let rec = make_recommendation(
            "Deprecate old API endpoint",
            "API needs cleanup",
            Priority::Warning,
        );
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        assert!(!suggestions.is_empty());
        assert!(suggestions.iter().any(|s| s.title.contains("Deprecation")));
    }

    #[test]
    fn test_generate_document_keyword_follow_up() {
        let rec = make_recommendation(
            "Update API documentation",
            "Docs need revision",
            Priority::Suggestion,
        );
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        assert!(!suggestions.is_empty());
        assert!(suggestions
            .iter()
            .any(|s| s.title.contains("Documentation")));
    }

    #[test]
    fn test_generate_critical_empty_provides_baseline() {
        let rec = make_recommendation(
            "Critical issue with no keywords",
            "Something important",
            Priority::Critical,
        );
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        // Should have at least the baseline critical follow-up
        assert!(!suggestions.is_empty());
    }

    #[test]
    fn test_generate_with_next_step() {
        let mut rec = make_recommendation("Fix memory leak", "Memory issue", Priority::Warning);
        rec.suggested_next_step =
            Some("Profile the application to find the leak source".to_string());
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        assert!(suggestions.iter().any(|s| s.title.contains("Next step")));
    }

    #[test]
    fn test_generate_batch() {
        let recs = vec![
            make_recommendation(
                "Fix security vulnerability",
                "Security issue",
                Priority::Critical,
            ),
            make_recommendation("Add unit test coverage", "Tests needed", Priority::Warning),
        ];
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate_batch(&recs);
        // Should have at least one follow-up per recommendation
        assert!(suggestions.len() >= 2);
    }

    #[test]
    fn test_deduplicate_suggestions() {
        // Create two recommendations that would produce duplicate titles
        let rec1 = make_recommendation("Fix test coverage", "Tests needed", Priority::Suggestion);
        let rec2 = make_recommendation("Improve test coverage", "More tests", Priority::Suggestion);
        let fu = ContextualFollowUp::new();
        let suggestions1 = fu.generate(&rec1);
        let suggestions2 = fu.generate(&rec2);
        // Both should produce "Consider adding more test coverage"
        // Deduplication should prevent identical titles
        let mut combined = suggestions1;
        combined.extend(suggestions2);
        let mut unique = combined.clone();
        let mut seen = std::collections::HashSet::new();
        unique.retain(|s| seen.insert(s.title.to_lowercase()));
        assert!(unique.len() <= combined.len());
    }

    #[test]
    fn test_follow_up_suggestion_has_id() {
        let rec = make_recommendation("Test", "Description", Priority::Suggestion);
        let fu = ContextualFollowUp::new();
        let suggestions = fu.generate(&rec);
        for suggestion in &suggestions {
            assert_ne!(suggestion.id, Uuid::nil());
            assert_eq!(suggestion.parent_recommendation_id, rec.id);
        }
    }

    #[test]
    fn test_contextual_follow_up_default() {
        let fu = ContextualFollowUp::default();
        assert_eq!(fu.generated_ids.len(), 0);
    }
}
