//! Wiki Labs AI Copilot Engine
//!
//! Transforms engineering understanding into timely, trustworthy,
//! context-aware guidance. The engineer remains fully in control.
//!
//! The AI never performs work autonomously.

pub mod approval;
pub mod cards;
pub mod conversation;
pub mod decision;
pub mod engine;
pub mod explainability;
pub mod follow_up;
pub mod lifecycle;
pub mod memory;
pub mod modes;
pub mod policy;
pub mod priority;
pub mod proactive;
pub mod recommendation;

// Re-exports
pub use approval::HumanApproval;
pub use cards::RecommendationCard;
pub use conversation::ConversationContext;
pub use decision::DecisionEngine;
pub use engine::CopilotEngine;
pub use explainability::Explainability;
pub use follow_up::ContextualFollowUp;
pub use lifecycle::{LifecycleState, RecommendationLifecycle};
pub use memory::SessionMemory;
pub use modes::{CopilotMode, ModeConfig};
pub use policy::PolicyEngine;
pub use proactive::ProactiveAssistance;
pub use recommendation::RecommendationEngine;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::fmt;

/// Confidence score for a recommendation (0.0 - 1.0)
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Confidence {
    pub score: f64,
}

impl Confidence {
    pub fn new(score: f64) -> Self {
        Confidence {
            score: score.clamp(0.0, 1.0),
        }
    }

    pub fn is_high(&self) -> bool {
        self.score >= 0.8
    }
    pub fn is_medium(&self) -> bool {
        self.score >= 0.5 && self.score < 0.8
    }
    pub fn is_low(&self) -> bool {
        self.score < 0.5
    }
}

impl fmt::Display for Confidence {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:.0}%", self.score * 100.0)
    }
}

/// Priority level for recommendations
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Priority {
    Critical,
    Warning,
    Suggestion,
    Information,
}

impl Priority {
    /// Returns true only for Critical priority. Used to determine
    /// which items pass Minimal policy filtering.
    pub fn is_urgent(&self) -> bool {
        matches!(self, Priority::Critical)
    }
}

impl fmt::Display for Priority {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Priority::Critical => write!(f, "Critical"),
            Priority::Warning => write!(f, "Warning"),
            Priority::Suggestion => write!(f, "Suggestion"),
            Priority::Information => write!(f, "Information"),
        }
    }
}

/// Evidence supporting a recommendation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Evidence {
    pub source: String,
    pub description: String,
    pub confidence: Confidence,
}

/// A recommendation generated by the copilot
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Recommendation {
    pub id: uuid::Uuid,
    pub title: String,
    pub description: String,
    pub reason: String,
    pub confidence: Confidence,
    pub evidence: Vec<Evidence>,
    pub priority: Priority,
    pub supporting_documents: Vec<String>,
    pub suggested_next_step: Option<String>,
    pub created_at: DateTime<Utc>,
    pub workflow_context: Option<String>,
}

impl Recommendation {
    pub fn new(
        title: impl Into<String>,
        description: impl Into<String>,
        reason: impl Into<String>,
        confidence: Confidence,
        evidence: Vec<Evidence>,
        priority: Priority,
        supporting_documents: Vec<String>,
    ) -> Self {
        Recommendation {
            id: uuid::Uuid::new_v4(),
            title: title.into(),
            description: description.into(),
            reason: reason.into(),
            confidence,
            evidence,
            priority,
            supporting_documents,
            suggested_next_step: None,
            created_at: Utc::now(),
            workflow_context: None,
        }
    }

    pub fn with_next_step(mut self, step: impl Into<String>) -> Self {
        self.suggested_next_step = Some(step.into());
        self
    }

    pub fn with_workflow_context(mut self, ctx: impl Into<String>) -> Self {
        self.workflow_context = Some(ctx.into());
        self
    }
}
